apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    system: pitstop
    app: customermanagementapi
  name: customermanagementapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customermanagementapi
  template:
    metadata:
      labels:
        system: pitstop
        app: customermanagementapi
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-password
              key: RABBITMQ_DEFAULT_PASS
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-password
              key: SA_PASSWORD
        image: marcoippel/customermanagementapi
        imagePullPolicy: IfNotPresent
        name: customermanagementapi
        ports:
        - containerPort: 5100
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        # securityContext:
        #   readOnlyRootFilesystem: true
        #   runAsNonRoot: true
      restartPolicy: Always
