apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pitstop
resources:
- customermanagementapi.yaml
- customermanagementapi-svc.yaml
- ns.yaml
images:
- name: marcoippel/customermanagementapi
  newTag: 1.0.0-f9b9b74
