apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pitstop-webapp
spec:
  rules:
  - host: pitstop.k8s.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webapp
            port:
              number: 7000