apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pitstop-webapp
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "https://foo.nl"
    http:
      paths:
      - backend:
          serviceName: webapp
          servicePort: 7000
        path: /