apiVersion: v1
kind: Service
metadata:
  labels:
    system: pitstop
    app: customermanagementapi
  name: customermanagementapi
spec:
  type: ClusterIP
  ports:
  - name: "http-5100"
    port: 5100
    targetPort: 5100
  selector:
    system: pitstop
    app: customermanagementapi    