apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pitstop
resources:
- workshopmanagementeventhandler.yaml
- ns.yaml
images:
- name: marcoippel/workshopmanagementeventhandler
  newTag: 1.0.0-d941aa5
