apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    system: pitstop
    app: workshopmanagementeventhandler
  name: workshopmanagementeventhandler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workshopmanagementeventhandler
  template:
    metadata:
      labels:
        system: pitstop
        app: workshopmanagementeventhandler
    spec:
      containers:
      - env:
        - name: PITSTOP_ENVIRONMENT
          value: Production
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-password
              key: RABBITMQ_DEFAULT_PASS
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-password
              key: SA_PASSWORD
        image: marcoippel/workshopmanagementeventhandler
        imagePullPolicy: IfNotPresent
        name: workshopmanagementeventhandler
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      restartPolicy: Always
