apiVersion: v1
data:
    SA_PASSWORD: ENC[AES256_GCM,data:3OEKz3xzLIvpXFfIJl8q/ITdLEbZusfP,iv:ybtU1oJB74r9+DTldTX6aNCq7YBUYFeDOfm1Ejdfyt0=,tag:A5sLWqHy2mekHEKizcra4A==,type:str]
kind: Secret
metadata:
    name: mssql-password
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-05-14T17:19:35Z'
    mac: ENC[AES256_GCM,data:w5FXgI+hYS6D5AuLqZY1Ag7gpEs2QpsgTr2atibQoSWbx/O2vmPa6YJx008Rmz/WYdtNMnEvc9aJuf2LqYW0xQKN4tpx3nyFAVMZ7bgrbiwFdv91v9ejTjazN4mB8ngcjQrEKSlu5VPeCLmjqIjNVdxiiqzhIIjtXoH0+c07suQ=,iv:3MEJEVA9hgC8XYybpcZnFx1Kg1sTEZwhD4g0L9cfwI0=,tag:l3f0Rtmq/TNVuIVRL05K/A==,type:str]
    pgp:
    -   created_at: '2021-05-14T17:19:35Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4cntefEcksHARAAiRFa8nXSsD1J+MEtimgHQcnrWozaUKvjoJID8hmjHtee
            Dj1IEFACfJShL7OaK61VCcBaHd4+0lpoUnhnQoXVAvx8mHwMnvFzVpf6ELOGZ2sR
            ezV9o3VsilUvh/KHJUWENmMtNWl04SJRx9R5vDpV4a1g2A1DUCRj8TQ+P6FSe0U+
            p0ShsjdOf2CkIZz64ov2iFz6Vs2/+zGmn3+HS+E5Yi1J44/VwyR5ruPhEyF235II
            9MixAhGKsKa15DjC15D+dKQ+l3GaAoDiZZHHdZqdbwc7EqDWl1ZewsUTeIn4wYTS
            ZY8kiCDvkC9S8X6PslEx0pAe+aevPnIjSv29COetAC9hu04jkkimvUvleBYqEDdt
            CMn3GAL+lShBmuHbY5eQ369ZmOqrPYeofzbF9lf0dTmmpQh6FO29exDip62eb/rN
            cxRW8YhrNdtRbAMUyGf/0hh4S0ujVq7z1swcdXo4qEUjvp5tdloQBlZ8LH8yEbzf
            wEVoOmuA40We0sZSy03n6jJtEDHkvSvBKZSG0Nn03hLUKw55CuL/XLGhhrEcLuQb
            N0FR4AiNfqrk5QZLVlmERZHCvNLZcKDAZww7EDHryA40Rwn+Tsrl4J+5+6wKFcF3
            8AuSDmicv9p66+hk2Ul5HHq8W4qSNBnH5RMEYi7A5tmtF5U2fYrLxu43ua3TyDLS
            XAH1U1przYG5DF4jw2NMVMv0G4InQQdYxOe/7aYv11r2JlWtDIpBJh9yKZJz/4PG
            ojLvKJk41b1c92B1j4mJLqJ1hCUqj3pWKsGfG4jWfHY9KwgmisFY6XAMUoGH
            =J9vW
            -----END PGP MESSAGE-----
        fp: A401C376B3DF675464C295669C9B8650B8F2E242
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
