apiVersion: v1
data:
    RABBITMQ_DEFAULT_PASS: ENC[AES256_GCM,data:c8J48L+2OA3gxk/aUYlpmM+LEqZUa7f5,iv:haN2lIf5oxG9kXpq3/zlgmQsqg+iwOzx8KaO3ynWEjg=,tag:c79BOy+dVp2PaQdthj3buA==,type:str]
kind: Secret
metadata:
    name: rabbitmq-password
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-05-14T17:19:52Z'
    mac: ENC[AES256_GCM,data:GGU6hsvRs/DfExDQgnHwfKsyAjq7QSL8TPNZB7FvrbVsNx4LGIaUJeurU0c/FnTQ8qJrnUFByUaI9MhgpMcFk5wVNT4r/m0216zHLLpfJfCNQ1UU4XYArufHc1k0DQl8KRaN/+s76hsYUVkrTSW396qr0hT/3B8UdIRE+98a+pc=,iv:7zmsdJvViv//DitOl2SaoxVSe8NeC5UexRo5/El30FM=,tag:5Fh2SXY9CiiCeMC05wTWhQ==,type:str]
    pgp:
    -   created_at: '2021-05-14T17:19:52Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4cntefEcksHARAAkfaQim40g2jNPRU5404JXR5rkhRTQ2R5AM2J42dn551E
            KtyiyRLJy/L2jWe6Ria1DTImGwYIg78Fx1zdg5h3nVSvYyhV/dXzJhBsN3vio/AM
            XWISrLcjP2kuBTASq7yV0Mn3Pd2T17WJkuJ3YDef4gTWzl4EGJu83+15tGRk2okw
            UlYeHSexaGmRzg8Y8DLsMT256hGqmklYGKm5HTzr2NTXI7jaFssHc4MOGggGG4RC
            2rOaHAOt0liqDeb3w9tElL9a9Sc1hcA5TVHgxC3JIA3RutX2ZVddx+GxNhWt9bPa
            GeM1a3fnFAxpJD2jrRSKcCg8E80fOfsJiJjtrHi4l+D4QdEPVL+rU11wHnNubld6
            gqzPa01ybca4GzbtZgBOXWJIdSKQuFZCz95bZGKDZH4VthLG5Mch5v3jYTX32ItD
            N0PJPT4XEH0H2lM7awvWAIjvBL1AdZ55B3E4GXTkk/HrreFwib0j61SaVwXXyEWM
            +hx1xzGiYsFPyuNRQxC5utVqkDz4T33UFkr3v1q+nElNwjWosjIsh+YYbz7MIjAi
            HQ1AlmUUKgMNOBnrwponAeTH0ngd0gvOaBRc9gt3Zyi8hRApF7gn+lx7A3c6un45
            oQlSYtu26u8nVvmkfB5SKo1GY7jeNFsxd83MNJzi02V5VvbwwhHWuRZrrWFK/EXS
            XgGGBHRDUvNBGvtsDVcIlpe9x8kKkpm4wuzcpF+w44E1njhP27hd1ANl9T/LO2OD
            mR16uZjidnrvm4Hvzs1jvIFO1KeLbnjMlcsKkKVDT3GOf0bhiOmy7HrUxG5brqc=
            =OIgX
            -----END PGP MESSAGE-----
        fp: A401C376B3DF675464C295669C9B8650B8F2E242
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
