apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    system: pitstop
    app: rabbitmq
    version: v1
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        system: pitstop
        app: rabbitmq
        version: v1
    spec:
      containers:
      - env:
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-password
              key: RABBITMQ_DEFAULT_PASS 
        - name: RABBITMQ_DEFAULT_USER
          value: rabbitmquser
        image: rabbitmq:3-management
        imagePullPolicy: IfNotPresent
        name: rabbitmq
        ports:
        - containerPort: 15672
        - containerPort: 5672
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        securityContext:  
          readOnlyRootFilesystem: true  
          runAsNonRoot: true
      restartPolicy: Always