apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pitstop
resources:
- vehiclemanagementapi-svc.yaml
- vehiclemanagementapi.yaml
- ns.yaml
images:
- name: marcoippel/vehiclemanagementapi
  newTag: 1.0.0-d941aa5
