apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - workshopmanagementapi-svc.yaml
  - workshopmanagementapi.yaml
  - ns.yaml
images:
- name: marcoippel/workshopmanagementapi
  newTag: 1.0.0-8ea09ed
