apiVersion: v1
kind: Service
metadata:
  labels:
    system: pitstop
    app: vehiclemanagementapi
  name: vehiclemanagementapi
spec:
  type: ClusterIP
  ports:
  - name: "http-5000"
    port: 5000
    targetPort: 5000
  selector:
    system: pitstop
    app: vehiclemanagementapi

