apiVersion: v1
kind: Service
metadata:
  labels:
    system: pitstop
    app: rabbitmq
    version: v1
  name: rabbitmq
spec:
  type: ClusterIP
  ports:
  - name: "http-admin"
    port: 15672
    targetPort: 15672
  - name: "data"
    port: 5672
    targetPort: 5672
  selector:
    system: pitstop
    app: rabbitmq
    version: v1
