apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    system: pitstop
    app: sqlserver
    version: v1
  name: sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        system: pitstop
        app: sqlserver
        version: v1
    spec:
      containers:
      - env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_PID
          value: Developer
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-password
              key: SA_PASSWORD
        image: microsoft/mssql-server-linux:latest
        imagePullPolicy: IfNotPresent
        name: sqlserver
        ports:
        - containerPort: 1433
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        # securityContext:
        #   readOnlyRootFilesystem: true
        #   runAsNonRoot: true
      restartPolicy: Always