apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    system: pitstop
    app: logserver
    version: v1
  name: logserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        system: pitstop
        app: logserver
        version: v1
    spec:
      containers:
      - env:
        - name: ACCEPT_EULA
          value: "Y"
        image: datalust/seq:latest
        imagePullPolicy: IfNotPresent
        name: logserver
        ports:
        - containerPort: 80
      restartPolicy: Always