apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    system: pitstop
    app: mailserver
    version: v1
  name: mailserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        system: pitstop
        app: mailserver
        version: v1
    spec:
      containers:
      - image: djfarrelly/maildev
        imagePullPolicy: IfNotPresent
        name: mailserver
        ports:
        - containerPort: 25
        - containerPort: 80
      restartPolicy: Always
