apiVersion: v1
kind: Service
metadata:
  labels:
    system: pitstop
    app: mailserver
    version: v1
  name: mailserver
spec:
  type: NodePort
  ports:
  - name: "smtp"
    port: 25
    targetPort: 25
  - name: "web"
    port: 4000
    targetPort: 80
    nodePort: 30002
  selector:
    system: pitstop
    app: mailserver
    version: v1
