apiVersion: v1
kind: Service
metadata:
  labels:
    system: pitstop
    app: sqlserver
    version: v1
  name: sqlserver
spec:
  type: NodePort
  ports:
  - name: "tds"
    port: 1433
    targetPort: 1433
    nodePort: 30000
  selector:
    system: pitstop
    app: sqlserver
    version: v1