apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    system: pitstop
    app: vehiclemanagementapi
    version: "1.0"
  name: vehiclemanagementapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        system: pitstop
        app: vehiclemanagementapi
        version: "1.0"
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        image: pitstop/vehiclemanagementapi:1.0
        imagePullPolicy: IfNotPresent
        name: vehiclemanagementapi
        ports:
        - containerPort: 5000
      restartPolicy: Always