apiVersion: v1
kind: Service
metadata:
  labels:
    system: pitstop
    app: vehiclemanagementapi
    version: "1.0"
  name: vehiclemanagementapi
spec:
  type: NodePort
  ports:
  - name: "http-5000"
    port: 5000
    targetPort: 5000
    nodePort: 30006
  selector:
    system: pitstop
    app: vehiclemanagementapi
    version: "1.0"

