apiVersion: v1
kind: Service
metadata:
  labels:
    system: pitstop
    app: workshopmanagementapi
    version: "1.0"
  name: workshopmanagementapi
spec:
  type: NodePort
  ports:
  - name: "http-5200"
    port: 5200
    targetPort: 5200
    nodePort: 30007
  selector:
    system: pitstop
    app: workshopmanagementapi
    version: "1.0"
