apiVersion: v1
kind: Service
metadata:
  labels:
    system: pitstop
    app: webapp
    version: "1.0"
  name: webapp
spec:
  type: ClusterIP
  ports:
  - name: "7000"
    port: 7000
    targetPort: 7000
  selector:
    system: pitstop
    app: webapp
    version: "1.0"

