apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- customermanagementapi.yaml
- customermanagementapi-svc.yaml
images:
- name: marcoippel/CustomerManagementAPI
  newTag: 1.0.0-043507b
- name: marcoippel/customermanagementapi
  newTag: 1.0.0-8ea09ed
