apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    system: pitstop
    app: webapp
    version: "1.0"
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        system: pitstop
        app: webapp
        version: "1.0"
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        image: pitstop/webapp:1.0
        imagePullPolicy: IfNotPresent
        name: webapp
        ports:
        - containerPort: 7000
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        securityContext:  
          readOnlyRootFilesystem: true  
          runAsNonRoot: true
      restartPolicy: Always
