apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    system: pitstop
    app: notificationservice
    version: "1.0"
  name: notificationservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        system: pitstop
        app: notificationservice
        version: "1.0"
    spec:
      containers:
      - env:
        - name: PITSTOP_ENVIRONMENT
          value: Production
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-password
              key: RABBITMQ_DEFAULT_PASS 
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-password
              key: SA_PASSWORD 
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        name: notificationservice
      restartPolicy: Always
