apiVersion: v1
kind: Service
metadata:
  labels:
    system: pitstop
    app: workshopmanagementapi
  name: workshopmanagementapi
spec:
  type: ClusterIP
  ports:
  - name: "http-5200"
    port: 5200
    targetPort: 5200
  selector:
    system: pitstop
    app: workshopmanagementapi

