apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    system: pitstop
    app: workshopmanagementapi
  name: workshopmanagementapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        system: pitstop
        app: workshopmanagementapi
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-password
              key: RABBITMQ_DEFAULT_PASS 
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-password
              key: SA_PASSWORD 
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        name: workshopmanagementapi
        ports:
        - containerPort: 5200
      restartPolicy: Always